"""Initial schema

Revision ID: 001
Revises: 
Create Date: 2024-01-15 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create tenants table
    op.create_table('tenants',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('api_key_hash', sa.String(length=255), nullable=False),
        sa.Column('api_key_prefix', sa.String(length=8), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('rate_limit', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('api_key_hash')
    )
    op.create_index('idx_tenants_api_key_prefix', 'tenants', ['api_key_prefix'], unique=False)
    op.create_index('idx_tenants_active', 'tenants', ['id'], unique=False, postgresql_where=sa.text('is_active = True'))
    
    # Create users table
    op.create_table('users',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('external_id', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('timezone', sa.String(length=50), nullable=False),
        sa.Column('display_name', sa.String(length=255), nullable=True),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'external_id')
    )
    op.create_index('idx_users_tenant_external', 'users', ['tenant_id', 'external_id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_index('idx_users_phone', 'users', ['phone'], unique=False, postgresql_where=sa.text('phone IS NOT NULL'))
    
    # Create user_channel_preferences table
    op.create_table('user_channel_preferences',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('channel', sa.String(length=20), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint("channel IN ('email', 'sms', 'webhook')", name='ck_user_prefs_channel'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'channel')
    )
    op.create_index('idx_prefs_user', 'user_channel_preferences', ['user_id'], unique=False)
    
    # Create quiet_hours table
    op.create_table('quiet_hours',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
        sa.Column('start_time', sa.Time(), nullable=False),
        sa.Column('end_time', sa.Time(), nullable=False),
        sa.Column('timezone', sa.String(length=50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint("day_of_week BETWEEN 0 AND 6", name='ck_quiet_hours_day'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'day_of_week')
    )
    op.create_index('idx_quiet_hours_user', 'quiet_hours', ['user_id'], unique=False)
    
    # Create templates table
    op.create_table('templates',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('slug', sa.String(length=255), nullable=False),
        sa.Column('email_subject', sa.String(length=500), nullable=True),
        sa.Column('email_body', sa.Text(), nullable=True),
        sa.Column('sms_body', sa.Text(), nullable=True),
        sa.Column('webhook_payload', sa.Text(), nullable=True),
        sa.Column('variables_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint("category IN ('transactional', 'marketing', 'alert', 'system')", name='ck_templates_category'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'slug')
    )
    op.create_index('idx_templates_tenant_slug', 'templates', ['tenant_id', 'slug'], unique=False)
    
    # Create notifications table
    op.create_table('notifications',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('template_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('requested_channels', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('resolved_channels', postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column('primary_channel', sa.String(length=20), nullable=False),
        sa.Column('priority', sa.String(length=10), nullable=False),
        sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('send_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('suppressed_by_quiet_hours', sa.Boolean(), nullable=False),
        sa.Column('bypass_quiet_hours', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("priority IN ('critical', 'high', 'normal', 'low')", name='ck_notifications_priority'),
        sa.CheckConstraint("status IN ('queued', 'processing', 'sent', 'delivered', 'failed', 'partial', 'cancelled')", name='ck_notifications_status'),
        sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifs_tenant', 'notifications', ['tenant_id'], unique=False)
    op.create_index('idx_notifs_user', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_notifs_status', 'notifications', ['status'], unique=False)
    op.create_index('idx_notifs_created', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notifs_scheduled', 'notifications', ['scheduled_at'], unique=False, postgresql_where=sa.text('scheduled_at IS NOT NULL'))
    op.create_index('idx_notifs_priority_status', 'notifications', ['priority', 'status'], unique=False, postgresql_where=sa.text("status IN ('queued', 'processing')"))
    
    # Create webhook_configs table
    op.create_table('webhook_configs',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('url', sa.String(length=2000), nullable=False),
        sa.Column('secret', sa.String(length=255), nullable=True),
        sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('max_retries', sa.Integer(), nullable=False),
        sa.Column('timeout_seconds', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('failure_count', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhook_tenant', 'webhook_configs', ['tenant_id'], unique=False)
    op.create_index('idx_webhook_active', 'webhook_configs', ['tenant_id'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    
    # Create deliveries table
    op.create_table('deliveries',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('notification_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('channel', sa.String(length=20), nullable=False),
        sa.Column('destination', sa.String(length=500), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('provider_id', sa.String(length=255), nullable=True),
        sa.Column('provider_code', sa.String(length=50), nullable=True),
        sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('attempt_count', sa.Integer(), nullable=False),
        sa.Column('max_attempts', sa.Integer(), nullable=False),
        sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_error', sa.Text(), nullable=True),
        sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('bounced_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('bounce_reason', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint("channel IN ('email', 'sms', 'webhook')", name='ck_deliveries_channel'),
        sa.CheckConstraint("status IN ('pending', 'processing', 'sent', 'delivered', 'failed', 'bounced', 'cancelled')", name='ck_deliveries_status'),
        sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deliveries_notif', 'deliveries', ['notification_id'], unique=False)
    op.create_index('idx_deliveries_status', 'deliveries', ['status'], unique=False)
    op.create_index('idx_deliveries_retry', 'deliveries', ['status', 'next_retry_at'], unique=False, postgresql_where=sa.text("status = 'failed' AND next_retry_at IS NOT NULL"))
    op.create_index('idx_deliveries_provider_id', 'deliveries', ['provider_id'], unique=False, postgresql_where=sa.text('provider_id IS NOT NULL'))
    
    # Create delivery_events table
    op.create_table('delivery_events',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('delivery_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('notification_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('from_status', sa.String(length=20), nullable=True),
        sa.Column('to_status', sa.String(length=20), nullable=False),
        sa.Column('event_type', sa.String(length=30), nullable=False),
        sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_delivery', 'delivery_events', ['delivery_id'], unique=False)
    op.create_index('idx_events_notification', 'delivery_events', ['notification_id'], unique=False)
    op.create_index('idx_events_created', 'delivery_events', ['created_at'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_created', table_name='delivery_events')
    op.drop_index('idx_events_notification', table_name='delivery_events')
    op.drop_index('idx_events_delivery', table_name='delivery_events')
    op.drop_table('delivery_events')
    op.drop_index('idx_deliveries_provider_id', table_name='deliveries')
    op.drop_index('idx_deliveries_retry', table_name='deliveries')
    op.drop_index('idx_deliveries_status', table_name='deliveries')
    op.drop_index('idx_deliveries_notif', table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index('idx_webhook_active', table_name='webhook_configs')
    op.drop_index('idx_webhook_tenant', table_name='webhook_configs')
    op.drop_table('webhook_configs')
    op.drop_index('idx_notifs_priority_status', table_name='notifications')
    op.drop_index('idx_notifs_scheduled', table_name='notifications')
    op.drop_index('idx_notifs_created', table_name='notifications')
    op.drop_index('idx_notifs_status', table_name='notifications')
    op.drop_index('idx_notifs_user', table_name='notifications')
    op.drop_index('idx_notifs_tenant', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_templates_tenant_slug', table_name='templates')
    op.drop_table('templates')
    op.drop_index('idx_quiet_hours_user', table_name='quiet_hours')
    op.drop_table('quiet_hours')
    op.drop_index('idx_prefs_user', table_name='user_channel_preferences')
    op.drop_table('user_channel_preferences')
    op.drop_index('idx_users_phone', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_tenant_external', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_tenants_active', table_name='tenants')
    op.drop_index('idx_tenants_api_key_prefix', table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
